CREATE SEQUENCE SQ_FE_SOCIEDAD
    START WITH 1
    INCREMENT BY 1 
    MINVALUE 1;	
--GO

CREATE SEQUENCE SQ_FE_ENVIO_DOCUMENTO
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1;
--GO

CREATE SEQUENCE SQ_FE_DOCUMENTO
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1;
--GO